### ISSUE TITLE
1.20.1 - 1.0.2 - Roughback Guitarfish Overspawn

### ISSUE THREAD

**Issue by Mecheon** [Peeko32213/UnusualFish2#7]
In Swamp biomes specifically, Roughback Guitarfish spawn in overwhelming numbers

**Comment by Mecheon** [comment]
Latest update has fixed this one, all functioning as expected

**Comment by DWX12** [comment]
![2024-02-20_14 37 39](https://github.com/Coda1552/UnusualFish/assets/37384543/66f99a2f-f941-4247-bbbc-1ca1b8b43b9b)

Version of mod: unusualfishmod-1.0.3
Forge version: 47.2.17

You better revisit this issue. Ignore some of the other entities in the screenshot as I have many other mods installed.
