### ISSUE TITLE
Mod seems to take  up a lots of TPS from the Server

### ISSUE THREAD

**Issue by ionutsoran** [Peeko32213/UnusualFish2#9]
Hello there! After installing unsual fish mod  1.0.3 on my hosted modded sever on 1.20.1-forge-47.2.20 I noticed it takes quite a lot of tps and it seemed unusual. So I usually use spark for profiling such tasks. I will leave you the spark link below and some screenshots to look at.

https://spark.lucko.me/rtkhVIbX59
https://spark.lucko.me/Dd0CBHBjKz
https://spark.lucko.me/OhRZALjLmU
https://spark.lucko.me/j3Udj2Bz2r
https://spark.lucko.me/wlkcJV2qZO

![image](https://github.com/Coda1552/UnusualFish/assets/19574829/ad1b069b-283d-48c7-900e-433bc7dc4f34)
![image](https://github.com/Coda1552/UnusualFish/assets/19574829/e64e3b0f-0cfc-497c-a108-fd55f542aa27)
![image](https://github.com/Coda1552/UnusualFish/assets/19574829/2569de17-72d4-4d70-b24f-ad1816780513)
![image](https://github.com/Coda1552/UnusualFish/assets/19574829/82436bdc-5e4f-43b0-bdea-a2a7f80bf3a3)
![image](https://github.com/Coda1552/UnusualFish/assets/19574829/5f7e5bd0-68e4-4595-a6a8-1ef67c477a38)

**Comment by Coda1552** [comment]
Should be fixed in 1.0.4, which will be released soon. Thanks!
